package com.example.hirdaramani.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SalaryDto implements Serializable {
    @Null(message = "Id will be autogenerated")
    private Integer salaryId;
    @NotBlank(message = "Id number can't be empty")
    @Pattern(regexp = "^20(1[1-9]|[2-9][0-9])$", message = "Invalid year")
    private String year;
    @Pattern(regexp = "^JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC$", message = "Invalid Month")
    private String month;
    @Positive
    private BigDecimal salary;
    @Null(message = "Id will be autogenerated")
    private LocalDateTime createdDateTime;
    @Positive
    private Integer employeeId;
}
